language: python

python:
    - '3.4'
    - '3.5'
    - '3.6'
    - '3.7-dev'

env:
    - PYTHONPATH=src

install:
    - pip install -r dev-requirements.txt

script:
    - pylint --rcfile=.pylintrc src/nicetypes
    - py.test --verbose --cov=src --cov-fail-under=100

deploy:
    provider: pypi
    user: tvuillemin
    password:
        secure: Q2zPRvKL+8nzsOWcvoyAwL32YlriMXVzlzX+Cw+fWJAzSrrhcSbqgT6PnYaE9o1NtsaQQ7QIjK650A6+7o1vg9/TB9YQx6dUh3eeqQO30UPkPuo7OyXROFgdf/Wi/qqtgMwtTQZiILW7p/DsuQEMlWUi1HtnqTUqZ32HJUCbb4iooRHDeKuLt9XgBWpi8+BrAhGBZaOxVULECESO1cXtRdYeb7p73DwWbzIg0mWLdRjdyEDq9bCcLLvcy5ICbw65uhI4vajguR9MZxfaII3euelC2p99fcemdTxqfTydv3b4Ry8O4Dma98lKCAsXC8496SmYUMsaCxOuVPmUbOR4kTlhnlXnNR1hbdLm5m3p6o0D71bolgF4BFhJ3Z9StjgglNWNyp3QMtre73eHFLl8U7e1bT6qUtwu1jpKXv0lGgCmlWODXALxuiCm/W74UfnhMb03ZtTrv+UXUlrppw1Doq5vgUdmCWTrVuz5uruV3KGvVUXTyFjG0ltDMIoAgNAArtG2+nP8wiuiNSjp9hayGF910/H/VDH2B1ooHMutbqwRsmW+jiqwyTBEM+u1nXiaujoWqLCyigizBjRqoGsFmi0qNjABCqKdLbugK/7f27P4vwr8ADutm4yr7tyzvD0qjzVrBZiQH5KwTQHTYWYFcm8XS8fCvR8kMgJfYznUHBc=
    distributions: sdist bdist_wheel
    on:
        tags: true

notifications:
    email: false
