language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch

env:
  - PYTHONPATH=src

install:
  - "pip install -r dev-requirements.txt"

script:
  - "pylint --rcfile=.pylintrc src/nicetypes"
  - "py.test --verbose --cov=src --cov-fail-under=100"
